### ISSUE TITLE
Following guide -  evt-pg-create-db fails - settings/message_store_postgres.json ?

### ISSUE THREAD

**Issue by autotelik** [eventide-project/message-store-postgres#11]
Following : http://docs.eventide-project.org/examples/quickstart.html

I have set user and password in :  `quickstart/settings/message_store_postgres.json`

Then run

$ bundle exec evt-pg-create-db

Generates output as if settings not used i.e. dbname not found, and does not set user

```
Installing Database
= = =

(DATABASE_NAME is not set. Default will be used.)
Database name is: message_store

Creating User: message_store
- - -
psql.bin: FATAL:  role "thomas.statter" does not exist
'''

Perhaps it's picking up $USER rather than the "user" field from settings/message_store_postgres.json

I tried to drill down into evt-message_store-postgres-database-1.0.0.0/scripts/evt-pg-create-db and gems/ruby/2.5.0/gems/evt-message_store-postgres-database-1.0.0.0/database/install.sh

but not clear to me why the settings are not being picked up

**Comment by autotelik** [comment]
Running following first, enables script to complete.  

export PGUSER=<my_user>


Guide is confusing, if settings/message_store_postgres.json are not actually used

**Comment by sbellware** [comment]
There are two workflows and two corresponding roles in play. One is the application, and the other is database administration.

It shouldn't be presumed that an application's database connection configuration and the configuration of connection used for database administration would be the same configuration. In fact, they simply cannot be.

Postgres dictates the ways and means of connecting to a database for the purposes of database administration.

Eventide dictates the ways and means that applicative (not administrative) elements connect to the database.

Eventide is not a database administration tool. It uses the standard tools that ship with Postgres - tools that are effectively industry-standardized by virtue of the fact that they are purveyed by Postgres. This is also true of Eventide's Event Store implementation. We do not intercede in the broader standards and conventions established by the particular database and database administration and administrators.

And most importantly, we do not take opinionated stances that contradict or override the a-priory means that Postgres has the authority to dictate and to establish standards and conventions for. And most significantly, we do not dictate any ways or means that degrade security principles and practices or database administration principles and practices.

The fundamental issue is this: An applicative connection does not have the rights to modify the implementation of a database unless that application is a database administration tool.

So, I appreciate that all this may be confusing, but I would posit that it's because the Eventide toolkit does not shield the user who may have previously been shielded from the concerns of database operations, and who has been thus far been able to treat the database as a black box behind the interface of an ORM.

More directly, what a developer can learn about database operations from ActiveRecord Migrations is only sufficient for the needs and concerns of ActiveRecord developers, to the detriment of the concerns of database operators. In cases where a developer is also wearing a database operator's hat, they must de facto put on that database operator's hat, and understand the conventional implications of wearing it. There's simply no getting around that.

Eventide does database operation the way that database operators do, and we cannot legitimately dictate that database operators adopt practices that are only suitable in a development environment. Such a move would cause the Eventide toolkit to become unviable.

Autonomous services as an architectural style - by its nature - demands and implies higher levels of maturity from an operations perspective. All the short cuts we're able to take in environments like Rails where prototyping techniques are dominant are categorically off the table.

The implication is that there is an expectation that the operator meets the minimum bar implied by the architecture. And sometimes that means learning more about the whole of the environment and its strictures. The database isn't a black box, and can't be, and we can't be liable for encouraging anything that might lead to treating it as such.

And thankfully, it only takes a few minutes of orientation to bridge that gap.

I hope this helps, and puts all this in perspective.

**Comment by autotelik** [comment]
Ok thanks for the extensive back ground

Given that your guide has a section

 Assure the Postgres Connection Settings

immediately followed by

 Create the Message Store Postgres Database

And you state
>>Postgres connection settings can be found in
>>The provided settings should work for the majority of development environment setups.

Its not clear to someone new, trying to access and evaluate your project, that the two are not connected in any way.


Yes in the end from searching through the scripts and code I worked out they were not connected and so was able to continue by export PGUSER=<my_user>

**Comment by sbellware** [comment]
I've added a note to explain that administrative connection are under the authority of Postgres' tools.

http://docs.eventide-project.org/examples/quickstart.html#create-the-message-store-postgres-database

**Comment by autotelik** [comment]
thank you that seems clearer for operators new to the space
